apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-pod
  template:
    metadata:
      name: app-pod
      labels:
        app: app-pod
    spec:
      containers:
        - name: mariadb-lanchonete
          image: thiagobsn/mariadb-lanchonete
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configmap-db
                  key: MARIADB_DATABASE
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: password
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: password