apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app-pod
spec:
  containers:
    - name: lanchonete-app
      image: thiagobsn/lanchonete-app
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: password
        - name: SPRING_JPA_SHOW
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: SPRING_JPA_SHOW
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL